ques 9: SELECT DISTINCT DEPARTMENT FROM WORKER;

ques 10: SELECT * FROM WORKER ORDER BY FIRST_NAME;

ques 11: SELECT * FROM WORKER 
         ORDER BY FIRST_NAME,DEPARTMENT DESC;
         
ques 12: SELECT * FROM WORKER 

         WHERE FIRST_NAME='Vipul' OR FIRST_NAME='Satish';
ques 13: SELECT * FROM WORKER 
         WHERE NOT(FIRST_NAME='Vipul' OR FIRST_NAME='Satish');
         
ques 14: SELECT * FROM WORKER WHERE DEPARTMENT='Admin';
 

