# Generated by Django 3.2.6 on 2021-08-27 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('director_name', models.CharField(max_length=50)),
                ('box_office', models.BigIntegerField()),
                ('release_date', models.DateField()),
                ('imdb_ratings', models.FloatField()),
            ],
        ),
    ]
