# Generated by Django 3.2.6 on 2021-08-28 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_alter_movie_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(default='https://via.placeholder.com/300', upload_to='movie\\images'),
        ),
    ]
