# Generated by Django 3.2.6 on 2021-08-30 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0011_rename_category_movie_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='verdict',
            field=models.CharField(default='ATB', max_length=10),
        ),
    ]
