# Generated by Django 3.2.6 on 2021-08-31 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0013_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='rent_price',
            field=models.FloatField(default=100.0),
        ),
    ]
